import pymysql
#全局变量
#账号
GLOBAL_PHONE=1

# 连接数据库操作
def connect_to_sql():
    db = pymysql.connect(host="localhost",port=3306, user="root", password="123456", database="kaoqin_db")
    # 使用cursor()方法获取操作游标
    cursor = db.cursor()
    return db, cursor
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Info_collection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


