# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import re

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 586)
        self.warninglabel = QtWidgets.QLabel(Form)
        self.warninglabel.setGeometry(QtCore.QRect(360, 180, 224, 22))
        self.warninglabel.setStyleSheet("color:red\n"
"")
        self.warninglabel.setObjectName("warninglabel")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(220, 300, 101, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.warninglabel_2 = QtWidgets.QLabel(Form)
        self.warninglabel_2.setGeometry(QtCore.QRect(360, 260, 224, 22))
        self.warninglabel_2.setStyleSheet("color:red\n"
"")
        self.warninglabel_2.setObjectName("warninglabel_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(252, 220, 70, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 400, 111, 41))
        self.pushButton.setStyleSheet("background-color:green;\n"
"    color:white;\n"
"border:0px;\n"
"border-radius:8px;\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(360, 210, 250, 41))
        self.lineEdit_4.setTabletTracking(False)
        self.lineEdit_4.setStyleSheet(" border:1px solid #ccc;\n"
" border-radius:4px;\n"
" color:#555;\n"
" padding: 6px 12px;\n"
"")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(250, 140, 70, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.warninglabel_3 = QtWidgets.QLabel(Form)
        self.warninglabel_3.setGeometry(QtCore.QRect(360, 340, 224, 22))
        self.warninglabel_3.setStyleSheet("color:red\n"
"")
        self.warninglabel_3.setObjectName("warninglabel_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 290, 251, 41))
        self.lineEdit_3.setStyleSheet("border:1px solid #ccc;\n"
"border-radius:4px;\n"
"color:#555;\n"
"padding: 6px 12px;\n"
"")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(358, 130, 250, 41))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_5.setTabletTracking(False)
        self.lineEdit_5.setStyleSheet(" border:1px solid #ccc;\n"
" border-radius:4px;\n"
" color:#555;\n"
" padding: 6px 12px;\n"
"")
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 400, 111, 41))
        self.pushButton_2.setStyleSheet("background-color:orange;\n"
"    color:white;\n"
"border:0px;\n"
"border-radius:8px;\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.warninglabel.hide()
        self.warninglabel_2.hide()
        self.warninglabel_3.hide()

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.updateSlot)
        self.lineEdit_5.editingFinished.connect(Form.checkOPwd)
        self.lineEdit_4.editingFinished.connect(Form.checkNPwd)
        self.lineEdit_3.editingFinished.connect(Form.checkNPPwd)
        # self.pushButton_2.clicked.connect(Form.closeSlot)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.warninglabel.setText(_translate("Form", "*旧密码错误！"))
        self.label_5.setText(_translate("Form", "确认新密码："))
        self.warninglabel_2.setText(_translate("Form", "*密码必须包含大小写字母和数字！"))
        self.label_6.setText(_translate("Form", "新密码："))
        self.pushButton.setText(_translate("Form", "确认"))
        self.label_7.setText(_translate("Form", "旧密码："))
        self.warninglabel_3.setText(_translate("Form", "*两次密码输入不一致！"))
        self.pushButton_2.setText(_translate("Form", "取消"))

    def checkNPwd(self):
            newpwd = self.lineEdit_4.text()
            if len(newpwd) == 0:
                    self.warninglabel_2.setText("*密码不得为空！")
                    self.warninglabel_2.show()

            else:
                    ret = re.match("^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])).*$", newpwd)
                    if ret == None:
                            self.warninglabel_2.setText("*密码必须包含大小写字母和数字！")
                            self.warninglabel_2.show()
                    else:
                            self.warninglabel_2.hide()


    def checkNPPwd(self):
            pwd = self.lineEdit_4.text()
            repwd = self.lineEdit_3.text()
            if len(repwd) == 0:
                    self.warninglabel_3.setText("*重新输入不得为空！")
                    self.warninglabel_3.show()

            else:
                    if pwd and repwd and pwd != repwd:
                            self.warninglabel_3.setText("*两次输入密码不一致！")
                            self.warninglabel_3.show()

                    else:
                            self.warninglabel_3.hide()

