# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clock_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, Qt, QTimer, QDateTime
from PyQt5.QtWidgets import QLabel, QMessageBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 639)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(330, 30, 181, 31))
        self.label_2.setStyleSheet("font: 11pt \"Agency FB\";\n"
"color: rgb(85, 255, 255);\n"
"font: 16pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 520, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 520, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(170, 80, 511, 431))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cameraArea_2 = QtWidgets.QLabel(self.widget)
        self.cameraArea_2.setMinimumSize(QtCore.QSize(480, 400))
        self.cameraArea_2.setMaximumSize(QtCore.QSize(480, 400))
        self.cameraArea_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.cameraArea_2.setText("")
        self.cameraArea_2.setObjectName("cameraArea_2")
        self.verticalLayout_2.addWidget(self.cameraArea_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 570, 551, 31))
        self.label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"")
        self.label.setObjectName("label")

        # 动态时间显示
        self.Timer = QTimer()
        self.Timer.start(500)
        self.Timer.timeout.connect(self.showtime)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    # 动态时间显示
    def showtime(self):
        datetime = QDateTime.currentDateTime()
        text = datetime.toString('yyyy-MM-dd hh:mm:ss dddd')
        self.label.setText(text)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "智慧考勤系统"))
        self.pushButton.setText(_translate("Form", "打开摄像头"))
        self.pushButton_2.setText(_translate("Form", "打卡"))
        self.label.setText(_translate("Form", "时间："))
