# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Info_collection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 639)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(510, 190, 331, 61))
        self.label_3.setStyleSheet("font: 25 11pt \"DengXian\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 161, 31))
        self.label_2.setStyleSheet("font: 11pt \"Agency FB\";\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 215, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 9pt \"Agency FB\";\n"
"font: 14pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.collcet_button = QtWidgets.QPushButton(Form)
        self.collcet_button.setGeometry(QtCore.QRect(175, 520, 111, 41))
        self.collcet_button.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.collcet_button.setObjectName("collcet_button")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(620, 140, 101, 31))
        self.label_4.setStyleSheet("font: 25 15pt \"DengXian\";\n"
"color: rgb(0, 85, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(510, 250, 331, 61))
        self.label_5.setStyleSheet("font: 25 11pt \"DengXian\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(510, 310, 331, 61))
        self.label_6.setStyleSheet("font: 25 11pt \"DengXian\";")
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 100, 400, 400))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraArea = QtWidgets.QLabel(self.widget)
        self.cameraArea.setGeometry(QtCore.QRect(1, 1, 400, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraArea.sizePolicy().hasHeightForWidth())
        self.cameraArea.setSizePolicy(sizePolicy)
        self.cameraArea.setMinimumSize(QtCore.QSize(400, 400))
        self.cameraArea.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.cameraArea.setFont(font)
        self.cameraArea.setStyleSheet("background-color:rgb(220, 220, 220);\n"
"")
        self.cameraArea.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraArea.setObjectName("cameraArea")
        self.verticalLayout.addWidget(self.cameraArea)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "1.新员工需要在本页面进行脸部信息采集，\n""否则后续无法进行每日打卡登记；\n"""))
        self.label_2.setText(_translate("Form", "脸部信息采集"))
        self.collcet_button.setText(_translate("Form", "开始采集"))
        self.label_4.setText(_translate("Form", "温馨提示："))
        self.label_5.setText(_translate("Form", "2.进行信息采集时请目视摄像头直到采集\n""完成；"))
        self.label_6.setText(_translate("Form", "3.请勿在光线较暗的环境中进行信息采集。"))
        self.cameraArea.setText(_translate("Form","<html><head/><body><p><img src=\":/pic/camera.png\"/></body></html>"))

import UI.pic_rc
