# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWin(object):
    def setupUi(self, LoginWin):
        LoginWin.setObjectName("LoginWin")
        LoginWin.resize(500, 470)
        LoginWin.setMaximumSize(QtCore.QSize(500, 470))
        LoginWin.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.label = QtWidgets.QLabel(LoginWin)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("line-weight:500;")
        self.label.setObjectName("label")
        self.PhoneNumInput = QtWidgets.QLineEdit(LoginWin)
        self.PhoneNumInput.setGeometry(QtCore.QRect(50, 120, 380, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.PhoneNumInput.setFont(font)
        self.PhoneNumInput.setText("")
        self.PhoneNumInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PhoneNumInput.setObjectName("PhoneNumInput")
        self.PwdInput = QtWidgets.QLineEdit(LoginWin)
        self.PwdInput.setGeometry(QtCore.QRect(50, 204, 380, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.PwdInput.setFont(font)
        self.PwdInput.setText("")
        self.PwdInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PwdInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PwdInput.setObjectName("PwdInput")
        self.LoginButton_staff = QtWidgets.QPushButton(LoginWin)
        self.LoginButton_staff.setGeometry(QtCore.QRect(50, 285, 380, 46))
        self.LoginButton_staff.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton_staff.setFont(font)
        self.LoginButton_staff.setObjectName("LoginButton_staff")
        self.SignupButton = QtWidgets.QPushButton(LoginWin)
        self.SignupButton.setGeometry(QtCore.QRect(50, 410, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignupButton.sizePolicy().hasHeightForWidth())
        self.SignupButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.SignupButton.setFont(font)
        self.SignupButton.setStyleSheet("border:0px;text-align:left;color:#999;background-color:#fff;padding:0;")
        self.SignupButton.setObjectName("SignupButton")
        self.ChangePwdButton = QtWidgets.QPushButton(LoginWin)
        self.ChangePwdButton.setGeometry(QtCore.QRect(340, 410, 90, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.ChangePwdButton.setFont(font)
        self.ChangePwdButton.setStyleSheet("border:0px;text-align:right;color:#999;background-color:#fff;padding:0;")
        self.ChangePwdButton.setObjectName("ChangePwdButton")
        self.LoginButton_hr = QtWidgets.QPushButton(LoginWin)
        self.LoginButton_hr.setGeometry(QtCore.QRect(50, 350, 380, 46))
        self.LoginButton_hr.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton_hr.setFont(font)
        self.LoginButton_hr.setObjectName("LoginButton_hr")
        self.warnLabel = QtWidgets.QLabel(LoginWin)
        self.warnLabel.setEnabled(True)
        self.warnLabel.setGeometry(QtCore.QRect(50, 176, 191, 16))
        self.warnLabel.setStyleSheet("color:red")
        self.warnLabel.setObjectName("warnLabel")
        self.warnLabel.hide()

        self.retranslateUi(LoginWin)
        self.LoginButton_staff.clicked.connect(LoginWin.verifySlot)
        self.LoginButton_hr.clicked.connect(LoginWin.verifySlot_hr)
        self.PhoneNumInput.editingFinished.connect(self.checkNum)
        QtCore.QMetaObject.connectSlotsByName(LoginWin)

    def checkNum(self):
        phoneNum = self.PhoneNumInput.text()
        if len(phoneNum)!= 11:
            self.warnLabel.show()
        else:
            self.warnLabel.hide()

    def retranslateUi(self, LoginWin):
        _translate = QtCore.QCoreApplication.translate
        LoginWin.setWindowTitle(_translate("LoginWin", "请登录"))
        self.label.setText(_translate("LoginWin", "欢迎使用"))
        self.PhoneNumInput.setPlaceholderText(_translate("LoginWin", "输入电话号码"))
        self.PwdInput.setPlaceholderText(_translate("LoginWin", "输入密码"))
        self.LoginButton_staff.setText(_translate("LoginWin", "员工登录"))
        self.SignupButton.setText(_translate("LoginWin", "手机号注册"))
        self.ChangePwdButton.setText(_translate("LoginWin", "忘记密码"))
        self.LoginButton_hr.setText(_translate("LoginWin", "HR登录"))
        self.warnLabel.setText(_translate("LoginWin", "手机号长度应为11位"))
