# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, Qt, QTimer, QDateTime
from PyQt5.QtWidgets import QLabel, QMessageBox


class CameraLabel(QLabel):
    clicked = pyqtSignal()
    def __init__(self,parent=None):
        super(CameraLabel,self).__init__(parent)

    def mouseReleaseEvent(self, QMouseEvent):
        if QMouseEvent.button() == Qt.LeftButton:
            self.clicked.emit()

class Ui_WelcomeWin(object):
    def setupUi(self, WelcomeWin):
        WelcomeWin.setObjectName("WelcomeWin")
        WelcomeWin.resize(902, 614)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        WelcomeWin.setFont(font)
        self.widget = QtWidgets.QWidget(WelcomeWin)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.signupButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signupButton.sizePolicy().hasHeightForWidth())
        self.signupButton.setSizePolicy(sizePolicy)
        self.signupButton.setMinimumSize(QtCore.QSize(150, 0))
        self.signupButton.setMaximumSize(QtCore.QSize(150, 44))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.signupButton.setFont(font)
        self.signupButton.setObjectName("signupButton")
        self.horizontalLayout.addWidget(self.signupButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setMinimumSize(QtCore.QSize(150, 0))
        self.loginButton.setMaximumSize(QtCore.QSize(150, 44))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 6)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 6)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(52, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 5, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        #self.cameraArea = QtWidgets.QLabel(self.widget)
        self.cameraArea = CameraLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraArea.sizePolicy().hasHeightForWidth())
        self.cameraArea.setSizePolicy(sizePolicy)
        self.cameraArea.setMinimumSize(QtCore.QSize(760, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.cameraArea.setFont(font)
        self.cameraArea.setStyleSheet("background-color:rgb(220, 220, 220);\n"
"")
        self.cameraArea.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraArea.setObjectName("cameraArea")
        self.verticalLayout.addWidget(self.cameraArea)
        self.timeLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(62)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("font-weight:500;")
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.verticalLayout.setStretch(0, 40)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 5, 1, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 7, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 20)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(2, 4)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(5, 30)
        self.gridLayout.setRowStretch(7, 3)
        WelcomeWin.setCentralWidget(self.widget)

        # 动态时间显示
        self.Timer = QTimer()
        self.Timer.start(500)
        self.Timer.timeout.connect(self.showtime)
        # 摄像头定时器
        self.timer_camera = QTimer()
        self.cap = cv2.VideoCapture()
        self.CAM_NUM = 0

        self.retranslateUi(WelcomeWin)
        self.loginButton.clicked.connect(WelcomeWin.loginSlot)
        self.signupButton.clicked.connect(WelcomeWin.signupSlot)
        self.cameraArea.clicked.connect(self.showdata)
        self.timer_camera.timeout.connect(WelcomeWin.showcamera)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWin)

    def showdata(self):
        if self.timer_camera.isActive() == False:
            flag = self.cap.open(self.CAM_NUM) #打开摄像头
            if flag == False:
                QMessageBox.warning(self,"警告","无法打开摄像头",QMessageBox.Yes)
            else:
                self.timer_camera.start(30)
        else:
            self.timer_camera.stop()
            self.cap.release()
            self.cameraArea.clear()

    def showcamera(self):
        flag,self.image = self.cap.read()
        show = cv2.resize(self.image,(self.cameraArea.width(),self.cameraArea.height()))
        show = cv2.cvtColor(show, cv2.COLOR_BGR2RGB)
        showImage = QtGui.QImage(show.data, show.shape[1], show.shape[0], QtGui.QImage.Format_RGB888)
        self.cameraArea.setPixmap(QtGui.QPixmap.fromImage(showImage))
    # 动态时间显示
    def showtime(self):
        datetime = QDateTime.currentDateTime()
        text = datetime.toString('yyyy-MM-dd hh:mm:ss dddd')
        self.timeLabel.setText(text)

    def retranslateUi(self, WelcomeWin):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWin.setWindowTitle(_translate("WelcomeWin", "智慧考勤系统"))
        self.label.setText(_translate("WelcomeWin", "智慧考勤系统"))
        self.signupButton.setText(_translate("WelcomeWin", "注册"))
        self.loginButton.setText(_translate("WelcomeWin", "登录"))
        self.cameraArea.setText(_translate("WelcomeWin", "<html><head/><body><p><img src=\":/pic/camera.png\"/></p><p>点击开启摄像头</p></body></html>"))
        self.timeLabel.setText(_translate("WelcomeWin", "时间"))
import UI.pic_rc